
version: '3'
services:
  app:
    build: ./
    volumes:
      - ./:/usr/local/app
    restart: always
    working_dir: /usr/local/app
    ports:
      - 3000:3000
    command: node server/server.js
